version: v1.0

prompt:
  title: "Demo"
  prefix: "demo >"
  history:
    limit: 100
    filename: .posh/history
    lockFilename: .posh/history.lock

env:
  GOPROXY: "https://proxy.golang.org,direct"
  PATH: "${PROJECT_ROOT}/node_modules/.bin:${PROJECT_ROOT}/bin:${PATH}"

plugin:
  source: .posh/plugin.go
  provider: New

packages:
  - name: gotsrpc
    version: 2.6.2
#  - name: helm
#    version: 3.8.1
#  - name: husky
#    version: 1.7.0
#  - name: hygen
#    version: 6.1.0
#  - name: k6
#    version: 0.34.1
#  - name: k9s
#    version: 0.24.15
#

dependencies:
  envs:
    - name: GITHUB_TOKEN
      help: |
        You need to export a GITHUB_TOKEN in your environment!

        To do so, create an access token on https://github.com/settings/tokens with the following permissions:

          - repo
          - write:packages
          - delete:packages

        and export it into your environment e.g. ZSH:

          $ vi ~/.zshenv

          export GITHUB_TOKEN=XXX
#  scripts:
#    - name: op
#      command: op account --account <ACCOUNT> get > /dev/null 2>&1
#      help: |
#        You're not yet logged into the 1Password account!
#
#        $ op signin <ACCOUNT>.1password.eu <EMAIL>
#    - name: npm
#      command: op account --account <ACCOUNT> get > /dev/null 2>&1
#      help: |
#        You're not yet logged into the github npm registry!
#
#          $ npm login --scope=@<SCOPE> --registry=https://npm.pkg.github.com
#          Username: [GITHUB_USERNAME]
#          Password: [GITHUB_TOKEN]
#          Email: [EMAIL]
  packages:
    - name: git
      version: '~2'
      command: git version | awk '{print $3}'
      help: |
        Please ensure you have 'git' installed in the required version: %s!

          $ brew update
          $ brew install git
    - name: go
      version: '>=1.19.4'
      command: go env GOVERSION | cut -c3-
      help: |
        Please ensure you have 'go' installed in the required version: %s!

          $ brew update
          $ brew install go
    - name: op
      version: '~2'
      command: op --version
      help: |
        Please ensure you have the 1Password cli 'op' installed in the required version: %s!

          $ brew update
          $ brew install 1password-cli
    - name: node
      version: '~16'
      command: node --version
      help: |
        Please ensure you have 'node' installed in the required version: %s!

        We strongly recommend installing 'nvm' trough:

          $ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

        If you already have installed 'nvm' just run the following command to read in the .nvmrc:

          $ nvm use
    - name: yarn
      version: '~1'
      command: yarn --version
      help: |
        Please ensure you have 'yarn' installed in the required version: %s!

          $ npm install -g yarn
    - name: tsh
      version: '>=10'
      command: tsh version --skip-version-check | awk 'NR==1{print $2}'
      help: |
        Please ensure you have 'teleport' installed in the required version: %s!

          $ brew update
          $ brew install teleport
    - name: goimports
      version: '>=2022'
      command: date -r $(which goimports) +%Y.%-m.%-d
      help: |
        Please ensure you have 'goimports' installed in a recent version: %s!

          $ go install golang.org/x/tools/cmd/goimports@latest

# 1Password
onePassword:
  account: <ACCOUNT>
  tokenFilename: .posh/config/.op
