# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2

multi-ecosystem-groups:
  all:
    schedule:
      day: 'sunday'
      interval: 'weekly'
      timezone: "Europe/Berlin"
    commit-message:
      prefix: 'deps'

updates:
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 1
    multi-ecosystem-groups: all
    patterns: ['*']
    directory: '/'
    allow:
      - dependency-type: 'all'
    cooldown:
      default-days: 1
      include: [ '*' ]

  - package-ecosystem: 'gomod'
    open-pull-requests-limit: 1
    multi-ecosystem-groups: all
    directories: ['**/*']
    patterns: ['*']
    allow:
      - dependency-type: all
    cooldown:
      default-days: 1
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 1
      include: [ '*' ]
