before:
  hooks:
    - go mod download
builds:
  - binary: posh
    main: ./main.go
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/foomo/posh/internal/version.Version={{.Version}}
      - -X github.com/foomo/posh/internal/version.CommitHash={{.FullCommit}}
      - -X github.com/foomo/posh/internal/version.BuildTimestamp={{.Timestamp}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - '^wip:'
      - '^docs:'
      - '^test:'
      - '^Merge'

brews:
  - tap:
      owner: foomo
      name: homebrew-tap
    caveats: "posh help"
    homepage: "https://github.com/foomo/posh"
    description: "Project Oriented SHELL"
