# yaml-language-server: $schema=config.schema.json
version: '1.0'

# Prompt settings
prompt:
  title: My title
  prefix: my-prefix

# Environment variables
env:
  - name: FOO
    value: bar

# Require settings
require:
  envs: []
  packages: []
  scripts: []
