name: Pull requests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: make test
      - run: make test.demo

