name: Releases Tag

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
          installation_id: ${{ secrets.TOKEN_APP_INSTALLATION_ID }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
